spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://3.141.100.171:5432/test
    username: postgres
    password: postgres
  jpa:
    database: postgresql
  profiles:
    active: stage
  flyway:
    placeholder-replacement: true
    out-of-order: true
    baseline-on-migrate: true
  transaction:
    default-timeout: 90
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth


database:
  url: 3.141.100.171
  username: postgres
  password: postgres
  dbName: test
  port: 5432
